import { domainsOf, domainMetaOf, dataClassOf } from '../data/schema.js';
import { computeDropSets } from './dropped.js';

function uid(prefix = 'x') {
  return `${prefix}_${Math.random().toString(36).slice(2, 9)}`;
}

/* ================================================================
   Exports
================================================================ */
// Fields marked for deletion are kept in the JSON export, so they're kept here
// too — but commented out rather than emitted as live DDL. The script stays
// runnable and produces the target schema, while the dropped columns remain
// visible to whoever reviews the diff.
//
// "Dropped" here means the canvas's hidden set: explicitly marked fields plus
// fields orphaned by a marked FK target. An orphaned column would reference a
// column that no longer exists, so it can't be emitted as live DDL either. A PK
// is never in that set.

export function buildSqlDdl(schema) {
  const tBy = Object.fromEntries(schema.tables.map(t => [t.id, t]));
  const { hidden: droppedFieldIds, marked, deadTableIds } = computeDropSets(schema.tables);
  const isDropped = (f) => droppedFieldIds.has(f.id);
  // A marked primary key is deliberately NOT in `hidden` — commenting it out
  // would leave an invalid table and strand every FK that targets it. It still
  // has to be annotated, or the decision vanishes from the DDL entirely.
  const keptButMarked = (f) => marked.has(f.id) && !droppedFieldIds.has(f.id);

  const colDef = (f) => {
    let s = `${f.name.padEnd(28)} ${f.type}`;
    if (f.pk) s += " PRIMARY KEY";
    if (!f.nullable && !f.pk) s += " NOT NULL";
    if (f.unique && !f.pk) s += " UNIQUE";
    return s;
  };

  const droppedTotal = droppedFieldIds.size;
  const lines = [];
  lines.push(`-- Generated by Schema Studio`);
  lines.push(`-- ${schema.tables.length} tables, ${schema.relationships.length} relationships`);
  if (droppedTotal > 0) {
    lines.push(`-- ${droppedTotal} field(s) marked for deletion are commented out, not omitted.`);
  }
  lines.push("");
  for (const t of schema.tables) {
    if (t.description) lines.push(`-- ${t.description}`);
    const live = t.fields.filter(f => !isDropped(f));
    const dropped = t.fields.filter(isDropped);

    // Two ways a table stops being creatable: nothing survives to declare, or
    // its primary key is on its way out so the rows have no identity. Either way
    // emit it as a comment — an empty CREATE TABLE isn't valid SQL, and a table
    // keyed on a doomed column isn't a table worth creating.
    if (live.length === 0 || deadTableIds.has(t.id)) {
      const why = deadTableIds.has(t.id)
        ? "its primary key is marked for deletion"
        : "every column is marked for deletion";
      lines.push(`-- TABLE ${t.name} — ${why}:`);
      for (const f of t.fields) lines.push(`--   ${colDef(f)}`);
      lines.push("");
      continue;
    }

    lines.push(`CREATE TABLE ${t.name} (`);
    // Commented columns go after the last live one so they can never disturb
    // the comma separators.
    lines.push(live.map((f, i) => {
      const note = keptButMarked(f) ? "   -- MARKED FOR DELETION (kept: primary key)" : "";
      // The trailing comment must follow the comma, not precede it.
      return `  ${colDef(f)}${i < live.length - 1 ? "," : ""}${note}`;
    }).join("\n"));
    for (const f of dropped) lines.push(`--  ${colDef(f)}   -- marked for deletion`);
    lines.push(`);`);
    for (const f of t.fields) {
      if (f.indexed && !f.pk && !f.unique) {
        const stmt = `CREATE INDEX idx_${t.name}_${f.name} ON ${t.name}(${f.name});`;
        lines.push(isDropped(f) ? `-- ${stmt}   -- column marked for deletion` : stmt);
      }
    }
    lines.push("");
  }
  lines.push("-- Foreign keys");
  for (const t of schema.tables) {
    for (const f of t.fields) {
      if (f.fk) {
        const target = tBy[f.fk.table];
        if (!target) continue;
        const targetField = target.fields.find(x => x.id === f.fk.field);
        if (!targetField) continue;
        const stmt = `ALTER TABLE ${t.name} ADD CONSTRAINT fk_${t.name}_${f.name} FOREIGN KEY (${f.name}) REFERENCES ${target.name}(${targetField.name});`;
        // The constraint can't stand if either column won't exist, or if either
        // table was emitted as a comment because it's dead.
        const deadEnd = droppedFieldIds.has(f.id) || droppedFieldIds.has(targetField.id);
        const deadTable = deadTableIds.has(t.id) || deadTableIds.has(target.id);
        lines.push(
          deadEnd || deadTable
            ? `-- ${stmt}   -- ${deadTable ? 'table is dead' : 'endpoint marked for deletion'}`
            : stmt
        );
      }
    }
  }
  return lines.join("\n");
}

export function buildMarkdownDoc(schema) {
  // Markdown documents the DECISION, so it keys off marked/orphaned rather than
  // the canvas's `hidden` set. Those differ for a marked primary key: it stays
  // visible on the canvas (relationships need the anchor) but the doc must still
  // record that it's on its way out.
  const { marked, orphaned, deadTableIds } = computeDropSets(schema.tables);
  const isStruck = (f) => marked.has(f.id) || orphaned.has(f.id);
  const lines = [];
  lines.push(`# Schema Documentation`);
  lines.push("");
  lines.push(`${schema.tables.length} tables across ${new Set(schema.tables.map(t => t.domain)).size} domains.`);
  lines.push("");

  const domains = domainsOf(schema.tables);
  const byDomain = {};
  for (const t of schema.tables) {
    (byDomain[t.domain] ||= []).push(t);
  }
  for (const [d, tables] of Object.entries(byDomain)) {
    lines.push(`## ${domainMetaOf(domains, d)?.name || 'Unassigned'}`);
    lines.push("");
    for (const t of tables) {
      const isDead = deadTableIds.has(t.id);
      lines.push(`### ${isDead ? `~~\`${t.name}\`~~ — DEAD` : `\`${t.name}\``}`);
      if (t.dataClass) lines.push(`*${dataClassOf(t.dataClass).label} data*`);
      lines.push("");
      if (isDead) {
        lines.push(`> **This table is finished.** Its primary key is marked for deletion (directly, or because the key it references is), so its rows have no identity left.`);
        lines.push("");
      }
      if (t.description) { lines.push(t.description); lines.push(""); }
      const markedN = t.fields.filter(f => marked.has(f.id)).length;
      const orphanN = t.fields.filter(f => orphaned.has(f.id)).length;
      if (markedN + orphanN > 0) {
        const causes = [
          markedN > 0 ? `${markedN} marked for deletion` : "",
          orphanN > 0 ? `${orphanN} orphaned by a marked FK target` : "",
        ].filter(Boolean).join(", ");
        lines.push(`> ${markedN + orphanN} of ${t.fields.length} fields struck through below — ${causes}.`);
        lines.push("");
      }
      lines.push(`| Field | Type | Key | Notes |`);
      lines.push(`|-------|------|-----|-------|`);
      for (const f of t.fields) {
        const key = f.pk ? "PK" : f.fk ? "FK" : f.unique ? "UQ" : f.indexed ? "IX" : "";
        const dropped = isStruck(f);
        const notes = [
          // Listed first so the disposition is the first thing read.
          orphaned.has(f.id)
            ? "**ORPHANED** (FK target marked for deletion)"
            : marked.has(f.id)
              ? (f.pk ? "**MARKED FOR DELETION** (kept: primary key)" : "**MARKED FOR DELETION**")
              : "",
          f.fk ? `→ ${schema.tables.find(x => x.id === f.fk.table)?.name}` : "",
          !f.nullable && !f.pk ? "NOT NULL" : "",
          f.description ? f.description.replace(/\|/g, "\\|") : "",
        ].filter(Boolean).join("; ");
        // Struck-through name keeps the row scannable without dropping the
        // record of what was there.
        const nameCell = dropped ? `~~\`${f.name}\`~~` : `\`${f.name}\``;
        lines.push(`| ${nameCell} | ${f.type} | ${key} | ${notes} |`);
      }
      lines.push("");
    }
  }
  return lines.join("\n");
}

/* ================================================================
   Mermaid erDiagram export
================================================================ */

// Mermaid identifiers must be alphanumeric / underscore. Replace anything else
// (spaces, slashes, dots) with underscores, then collapse runs and strip
// leading/trailing underscores. The resulting id is also used to label
// relationships, so we keep it stable per-table.
function mermaidId(name) {
  return name
    .replace(/[^A-Za-z0-9_]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
}

// Mermaid is picky about field type tokens: `varchar(255)` and `numeric(14,3)`
// will trip the parser. Convert parens/commas/spaces into underscores so the
// length / precision info stays readable.
function mermaidType(type) {
  if (!type) return 'unknown';
  return type
    .toString()
    .replace(/[()\s]+/g, '_')
    .replace(/,/g, '_')
    .replace(/[^A-Za-z0-9_]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '') || 'unknown';
}

// Map our relationship "type" strings to Mermaid cardinality glyphs. We treat
// non-null on the FK side as mandatory (||), nullable as optional (o|). Most
// of the demo data uses 'N:1' which renders as }o--|| (many optional → one).
function mermaidCardinality(type) {
  switch ((type || '').toUpperCase()) {
    case '1:1':  return '||--||';
    case '1:N':
    case '1:M':  return '||--o{';
    case 'M:N':
    case 'M:M':
    case 'N:M':  return '}o--o{';
    case 'N:1':
    case 'M:1':
    default:     return '}o--||';
  }
}

// Truncate + escape for a Mermaid inline comment (the `"..."` after a field).
function mermaidComment(s, max = 60) {
  if (!s) return '';
  let t = s.toString().replace(/\s+/g, ' ').trim();
  if (t.length > max) t = t.slice(0, max - 1).trimEnd() + '…';
  return t.replace(/"/g, "'");
}

export function buildMermaid(schema, opts = {}) {
  const includeComments = opts.includeComments !== false;
  const tBy = Object.fromEntries(schema.tables.map(t => [t.id, t]));
  // Mermaid has no way to render a field as struck-through, and this export is a
  // picture of the target model — the same thing the canvas shows. So dropped
  // fields are left out here rather than annotated, and a header comment records
  // how many were withheld.
  const { hidden: droppedFieldIds, deadTableIds } = computeDropSets(schema.tables);
  // Two reasons a table leaves the diagram: nothing is left to draw (which would
  // emit an empty `entity { }` block, and Mermaid may reject that), or it's dead
  // because its key is going. Relationships touching either are dropped below,
  // so nothing ends up pointing at a missing entity.
  const emptyTables = schema.tables.filter(
    t => deadTableIds.has(t.id)
      || (t.fields.length > 0 && t.fields.every(f => droppedFieldIds.has(f.id)))
  );
  const emptyTableIds = new Set(emptyTables.map(t => t.id));

  const lines = [];
  lines.push('%%{init: { "theme": "default" } }%%');
  if (droppedFieldIds.size > 0) {
    lines.push(`%% ${droppedFieldIds.size} field(s) marked for deletion are omitted from this diagram.`);
  }
  if (emptyTables.length > 0) {
    lines.push(`%% Dead or fully dropped, omitted: ${emptyTables.map(t => t.name).join(', ')}`);
  }
  lines.push('erDiagram');

  // Table declarations
  for (const t of schema.tables) {
    if (emptyTableIds.has(t.id)) continue;
    const tid = mermaidId(t.name);
    lines.push(`    ${tid} {`);
    for (const f of t.fields) {
      if (droppedFieldIds.has(f.id)) continue;
      const type = mermaidType(f.type);
      const fname = mermaidId(f.name);    // field names also sanitised
      const keyTag = f.pk ? ' PK' : f.fk ? ' FK' : f.unique ? ' UK' : '';
      const cmt = includeComments && f.description
        ? ` "${mermaidComment(f.description)}"`
        : '';
      lines.push(`        ${type} ${fname}${keyTag}${cmt}`);
    }
    lines.push('    }');
  }

  // Relationships
  if (schema.relationships.length > 0) lines.push('');
  // Mermaid can be sensitive to duplicate-arrow rendering. Dedupe by table-pair
  // + label so a many-FK situation between the same two tables doesn't render
  // ten overlapping arrows.
  const seen = new Set();
  for (const r of schema.relationships) {
    const fromT = tBy[r.from.table];
    const toT = tBy[r.to.table];
    if (!fromT || !toT) continue;
    // A relationship whose endpoint field isn't drawn would be an arrow to a
    // field that isn't in the diagram; likewise for an omitted entity.
    if (droppedFieldIds.has(r.from.field) || droppedFieldIds.has(r.to.field)) continue;
    if (emptyTableIds.has(fromT.id) || emptyTableIds.has(toT.id)) continue;
    const ff = fromT.fields.find(f => f.id === r.from.field)?.name || '';
    const cardinality = mermaidCardinality(r.type);
    const key = `${fromT.id}|${toT.id}|${ff}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const label = ff ? `"${ff}"` : '"references"';
    lines.push(`    ${mermaidId(fromT.name)} ${cardinality} ${mermaidId(toT.name)} : ${label}`);
  }

  return lines.join('\n');
}

/* ================================================================
   SQL DDL import — best-effort parser

   Supports:
     CREATE TABLE [IF NOT EXISTS] name (
       col TYPE [PRIMARY KEY] [NOT NULL] [UNIQUE] [REFERENCES other(col)],
       ...
       PRIMARY KEY (col),
       UNIQUE (col),
       FOREIGN KEY (col) REFERENCES other(col),
       CONSTRAINT name ...
     );
     ALTER TABLE name ADD [CONSTRAINT name] FOREIGN KEY (col) REFERENCES other(col);
     CREATE [UNIQUE] INDEX [name] ON table (col);

   Quoted identifiers: "name" or `name`
   Comments: line comments and C-style block comments.
   Unrecognized statements produce a warning and are skipped.
================================================================ */

function stripComments(src) {
  let out = '';
  let i = 0;
  while (i < src.length) {
    if (src[i] === '-' && src[i + 1] === '-') {
      while (i < src.length && src[i] !== '\n') i++;
    } else if (src[i] === '/' && src[i + 1] === '*') {
      i += 2;
      while (i < src.length && !(src[i] === '*' && src[i + 1] === '/')) i++;
      i += 2;
    } else {
      out += src[i++];
    }
  }
  return out;
}

function splitStatements(src) {
  const out = [];
  let depth = 0;
  let buf = '';
  let inStr = null;
  for (let i = 0; i < src.length; i++) {
    const c = src[i];
    if (inStr) {
      buf += c;
      if (c === inStr && src[i - 1] !== '\\') inStr = null;
      continue;
    }
    if (c === "'" || c === '"' || c === '`') { inStr = c; buf += c; continue; }
    if (c === '(') depth++;
    else if (c === ')') depth--;
    if (c === ';' && depth === 0) {
      const s = buf.trim();
      if (s) out.push(s);
      buf = '';
    } else {
      buf += c;
    }
  }
  const tail = buf.trim();
  if (tail) out.push(tail);
  return out;
}

function unquoteIdent(s) {
  s = s.trim();
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith('`') && s.endsWith('`'))) {
    return s.slice(1, -1);
  }
  return s;
}

// Split a parenthesised comma list at top-level commas only.
function splitTopLevel(body) {
  const out = [];
  let depth = 0;
  let buf = '';
  let inStr = null;
  for (let i = 0; i < body.length; i++) {
    const c = body[i];
    if (inStr) {
      buf += c;
      if (c === inStr && body[i - 1] !== '\\') inStr = null;
      continue;
    }
    if (c === "'" || c === '"' || c === '`') { inStr = c; buf += c; continue; }
    if (c === '(') depth++;
    else if (c === ')') depth--;
    if (c === ',' && depth === 0) {
      out.push(buf.trim());
      buf = '';
    } else {
      buf += c;
    }
  }
  if (buf.trim()) out.push(buf.trim());
  return out;
}

// Pull "name" or `name` or bareword off the front. Returns [ident, rest].
function takeIdent(s) {
  s = s.trimStart();
  if (s[0] === '"' || s[0] === '`') {
    const q = s[0];
    const end = s.indexOf(q, 1);
    if (end === -1) return [s.slice(1), ''];
    return [s.slice(1, end), s.slice(end + 1)];
  }
  const m = s.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*(.*)$/s);
  if (!m) return [null, s];
  return [m[1], m[2]];
}

// Pull "name.col" or "name(col)" — returns [tableName, colName, rest]
function takeQualified(s) {
  let [a, rest] = takeIdent(s);
  if (!a) return [null, null, s];
  rest = rest.trimStart();
  if (rest[0] === '.') {
    const [b, r2] = takeIdent(rest.slice(1));
    return [a, b, r2];
  }
  if (rest[0] === '(') {
    const close = rest.indexOf(')');
    if (close === -1) return [a, null, rest];
    const inside = rest.slice(1, close);
    const [b] = takeIdent(inside);
    return [a, b, rest.slice(close + 1)];
  }
  return [a, null, rest];
}

// Take a type token plus any parenthesised modifier and optional "with time zone" etc.
function takeType(s) {
  s = s.trimStart();
  // capture base type word (may include spaces for "double precision", "with time zone")
  const baseMatch = s.match(/^([A-Za-z_][A-Za-z0-9_]*)/);
  if (!baseMatch) return [null, s];
  let type = baseMatch[1];
  let rest = s.slice(type.length);
  // optional (...)
  rest = rest.trimStart();
  if (rest[0] === '(') {
    let depth = 0;
    let i = 0;
    for (; i < rest.length; i++) {
      if (rest[i] === '(') depth++;
      else if (rest[i] === ')') { depth--; if (depth === 0) { i++; break; } }
    }
    type += rest.slice(0, i);
    rest = rest.slice(i);
  }
  // trailing modifiers — "with time zone", "without time zone", "precision", "varying", "unsigned"
  const trailers = [
    /^with\s+time\s+zone\b/i,
    /^without\s+time\s+zone\b/i,
    /^precision\b/i,
    /^varying\b/i,
    /^unsigned\b/i,
  ];
  let changed = true;
  while (changed) {
    changed = false;
    rest = rest.replace(/^\s+/, '');
    for (const re of trailers) {
      const m = rest.match(re);
      if (m) { type += ' ' + m[0]; rest = rest.slice(m[0].length); changed = true; break; }
    }
  }
  return [type, rest];
}

function parseColumnDef(piece) {
  // piece: "name type CONSTRAINTS..."
  let [name, rest] = takeIdent(piece);
  if (!name) return null;
  const [type, after] = takeType(rest);
  if (!type) return null;
  const tail = after.trim();
  const upper = ' ' + tail.toUpperCase() + ' ';
  const col = {
    name,
    type,
    pk: /\sPRIMARY\s+KEY\s/.test(upper),
    notNull: /\sNOT\s+NULL\s/.test(upper),
    unique: /\sUNIQUE\s/.test(upper),
    refs: null,
  };
  // REFERENCES othertable(col)
  const refMatch = tail.match(/REFERENCES\s+(`[^`]+`|"[^"]+"|[A-Za-z_][A-Za-z0-9_]*)\s*\(\s*(`[^`]+`|"[^"]+"|[A-Za-z_][A-Za-z0-9_]*)\s*\)/i);
  if (refMatch) {
    col.refs = { table: unquoteIdent(refMatch[1]), column: unquoteIdent(refMatch[2]) };
  }
  return col;
}

function parseTableConstraint(piece) {
  // piece begins with a keyword: PRIMARY KEY | UNIQUE | FOREIGN KEY | CONSTRAINT
  const upper = piece.toUpperCase();
  let body = piece;
  // skip "CONSTRAINT name"
  if (/^CONSTRAINT\b/i.test(body)) {
    body = body.replace(/^CONSTRAINT\s+(`[^`]+`|"[^"]+"|[A-Za-z_][A-Za-z0-9_]*)\s+/i, '');
  }
  if (/^PRIMARY\s+KEY\b/i.test(body)) {
    const m = body.match(/\(\s*(.+?)\s*\)/);
    if (!m) return null;
    const cols = splitTopLevel(m[1]).map(unquoteIdent);
    return { kind: 'pk', columns: cols };
  }
  if (/^UNIQUE\b/i.test(body)) {
    const m = body.match(/\(\s*(.+?)\s*\)/);
    if (!m) return null;
    const cols = splitTopLevel(m[1]).map(unquoteIdent);
    return { kind: 'unique', columns: cols };
  }
  if (/^FOREIGN\s+KEY\b/i.test(body)) {
    const m = body.match(/FOREIGN\s+KEY\s*\(\s*(.+?)\s*\)\s*REFERENCES\s+(`[^`]+`|"[^"]+"|[A-Za-z_][A-Za-z0-9_]*)\s*\(\s*(.+?)\s*\)/i);
    if (!m) return null;
    const cols = splitTopLevel(m[1]).map(unquoteIdent);
    const refCols = splitTopLevel(m[3]).map(unquoteIdent);
    return { kind: 'fk', columns: cols, refTable: unquoteIdent(m[2]), refColumns: refCols };
  }
  return null;
}

function parseCreateTable(stmt) {
  // CREATE TABLE [IF NOT EXISTS] name ( body )
  const m = stmt.match(/^CREATE\s+(?:TEMP(?:ORARY)?\s+)?TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(`[^`]+`|"[^"]+"|[A-Za-z_][A-Za-z0-9_.]*)\s*\(/i);
  if (!m) return null;
  const name = unquoteIdent(m[1]).split('.').pop();
  // find balanced body
  const openIdx = stmt.indexOf('(', m.index + m[0].length - 1);
  let depth = 0;
  let close = -1;
  let inStr = null;
  for (let i = openIdx; i < stmt.length; i++) {
    const c = stmt[i];
    if (inStr) {
      if (c === inStr && stmt[i - 1] !== '\\') inStr = null;
      continue;
    }
    if (c === "'" || c === '"' || c === '`') { inStr = c; continue; }
    if (c === '(') depth++;
    else if (c === ')') { depth--; if (depth === 0) { close = i; break; } }
  }
  if (close === -1) return null;
  const body = stmt.slice(openIdx + 1, close);

  const pieces = splitTopLevel(body);
  const columns = [];
  const constraints = [];
  for (const p of pieces) {
    if (/^(CONSTRAINT|PRIMARY\s+KEY|UNIQUE|FOREIGN\s+KEY|CHECK|EXCLUDE)\b/i.test(p)) {
      const c = parseTableConstraint(p);
      if (c) constraints.push(c);
    } else {
      const c = parseColumnDef(p);
      if (c) columns.push(c);
    }
  }
  return { name, columns, constraints };
}

function parseAlterAddFk(stmt) {
  const m = stmt.match(/^ALTER\s+TABLE\s+(?:ONLY\s+)?(`[^`]+`|"[^"]+"|[A-Za-z_][A-Za-z0-9_.]*)\s+ADD\s+(?:CONSTRAINT\s+\S+\s+)?FOREIGN\s+KEY\s*\(\s*(.+?)\s*\)\s*REFERENCES\s+(`[^`]+`|"[^"]+"|[A-Za-z_][A-Za-z0-9_.]*)\s*\(\s*(.+?)\s*\)/i);
  if (!m) return null;
  const table = unquoteIdent(m[1]).split('.').pop();
  const cols = splitTopLevel(m[2]).map(unquoteIdent);
  const refTable = unquoteIdent(m[3]).split('.').pop();
  const refCols = splitTopLevel(m[4]).map(unquoteIdent);
  return { table, columns: cols, refTable, refColumns: refCols };
}

function parseCreateIndex(stmt) {
  const m = stmt.match(/^CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?(?:IF\s+NOT\s+EXISTS\s+)?(?:\S+\s+)?ON\s+(`[^`]+`|"[^"]+"|[A-Za-z_][A-Za-z0-9_.]*)\s*(?:USING\s+\S+\s*)?\(\s*(.+?)\s*\)/i);
  if (!m) return null;
  const isUnique = /^CREATE\s+UNIQUE/i.test(stmt);
  const table = unquoteIdent(m[1]).split('.').pop();
  const cols = splitTopLevel(m[2]).map(c => unquoteIdent(c.replace(/\s+(ASC|DESC)\b.*$/i, '')));
  return { table, columns: cols, unique: isUnique };
}

export function parseSqlDdl(src) {
  const warnings = [];
  const cleaned = stripComments(src);
  const statements = splitStatements(cleaned);

  // pass 1: tables
  const tablesByName = {};
  const tableOrder = [];
  // pass 2 deferred: indexes + alter-add-fk
  const indexes = [];
  const alterFks = [];

  for (const stmt of statements) {
    const head = stmt.replace(/\s+/g, ' ').slice(0, 24).toUpperCase();
    if (head.startsWith('CREATE TABLE') || head.startsWith('CREATE TEMP') || head.startsWith('CREATE TEMPORARY')) {
      const parsed = parseCreateTable(stmt);
      if (!parsed) { warnings.push(`Skipped CREATE TABLE: could not parse (${stmt.slice(0, 60)}…)`); continue; }
      if (tablesByName[parsed.name]) { warnings.push(`Duplicate table "${parsed.name}" — keeping the first`); continue; }
      tablesByName[parsed.name] = parsed;
      tableOrder.push(parsed.name);
    } else if (head.startsWith('ALTER TABLE')) {
      const fk = parseAlterAddFk(stmt);
      if (fk) alterFks.push(fk);
      else warnings.push(`Skipped ALTER TABLE (only ADD FOREIGN KEY supported)`);
    } else if (head.startsWith('CREATE INDEX') || head.startsWith('CREATE UNIQUE INDEX')) {
      const idx = parseCreateIndex(stmt);
      if (idx) indexes.push(idx);
      else warnings.push(`Skipped CREATE INDEX: could not parse`);
    } else if (head === '') {
      // empty
    } else {
      warnings.push(`Skipped unrecognised statement: ${stmt.slice(0, 60).replace(/\s+/g, ' ')}…`);
    }
  }

  if (tableOrder.length === 0) {
    throw new Error('No CREATE TABLE statements found.');
  }

  // Build schema model
  const tables = [];
  const fieldIdByCol = {}; // tablesByName[tname].fieldIds[colName] -> fieldId

  // Grid layout
  const COLS = 4;
  const CELL_W = 340;
  const CELL_H = 360;

  tableOrder.forEach((tname, idx) => {
    const parsed = tablesByName[tname];
    const tableId = uid('t');
    const col = idx % COLS;
    const row = Math.floor(idx / COLS);

    const pkCols = new Set();
    const uniqueCols = new Set();
    const fkRefs = []; // {col, refTable, refCol}

    // From column-level
    for (const c of parsed.columns) {
      if (c.pk) pkCols.add(c.name);
      if (c.unique) uniqueCols.add(c.name);
      if (c.refs) fkRefs.push({ col: c.name, refTable: c.refs.table, refCol: c.refs.column });
    }
    // From table-level constraints
    for (const k of parsed.constraints) {
      if (k.kind === 'pk') k.columns.forEach(c => pkCols.add(c));
      else if (k.kind === 'unique') k.columns.forEach(c => uniqueCols.add(c));
      else if (k.kind === 'fk') {
        k.columns.forEach((c, i) => {
          fkRefs.push({ col: c, refTable: k.refTable, refCol: k.refColumns[i] || k.refColumns[0] });
        });
      }
    }

    const fields = parsed.columns.map(c => {
      const fId = uid('f');
      const isPk = pkCols.has(c.name);
      return {
        id: fId,
        name: c.name,
        type: c.type,
        pk: isPk,
        fk: null,            // resolved in pass 2
        unique: uniqueCols.has(c.name) && !isPk,
        indexed: false,      // resolved in pass 2 via CREATE INDEX
        nullable: !c.notNull && !isPk,
        description: '',
        example: '',
        warning: null,
        drop: false,
      };
    });

    fieldIdByCol[tname] = Object.fromEntries(fields.map(f => [f.name, f.id]));

    tables.push({
      id: tableId,
      name: tname,
      domain: 'unassigned',
      x: 80 + col * CELL_W,
      y: 80 + row * CELL_H,
      dataClass: null,
      description: '',
      purpose: '',
      owningDomain: null,
      consumingDomains: [],
      sourceOfTruth: null,
      syncDirection: null,
      writeOwner: null,
      readConsumers: [],
      changeFrequency: 'medium',
      sensitivity: 'internal',
      fields,
      _pendingFks: fkRefs, // resolved below
    });
  });

  const tableIdByName = Object.fromEntries(tables.map(t => [t.name, t.id]));
  const relationships = [];
  const seenRel = new Set();
  const addRel = (fromT, fromF, toT, toF) => {
    const key = `${fromT}.${fromF}->${toT}.${toF}`;
    if (seenRel.has(key)) return;
    seenRel.add(key);
    relationships.push({
      id: uid('r'),
      from: { table: fromT, field: fromF },
      to: { table: toT, field: toF },
      type: 'N:1',
    });
  };

  // Resolve inline FKs
  for (const t of tables) {
    for (const fkRef of t._pendingFks) {
      const targetTableId = tableIdByName[fkRef.refTable];
      const targetFieldId = fieldIdByCol[fkRef.refTable]?.[fkRef.refCol];
      const sourceFieldId = fieldIdByCol[t.name]?.[fkRef.col];
      if (!targetTableId || !targetFieldId || !sourceFieldId) {
        warnings.push(`Unresolved FK ${t.name}.${fkRef.col} -> ${fkRef.refTable}.${fkRef.refCol}`);
        continue;
      }
      const field = t.fields.find(f => f.id === sourceFieldId);
      if (field) field.fk = { table: targetTableId, field: targetFieldId };
      addRel(t.id, sourceFieldId, targetTableId, targetFieldId);
    }
    delete t._pendingFks;
  }

  // Resolve ALTER TABLE FKs
  for (const alt of alterFks) {
    const tId = tableIdByName[alt.table];
    if (!tId) { warnings.push(`ALTER TABLE for unknown table "${alt.table}"`); continue; }
    const t = tables.find(tt => tt.id === tId);
    for (let i = 0; i < alt.columns.length; i++) {
      const col = alt.columns[i];
      const refCol = alt.refColumns[i] || alt.refColumns[0];
      const sourceFieldId = fieldIdByCol[alt.table]?.[col];
      const targetTableId = tableIdByName[alt.refTable];
      const targetFieldId = fieldIdByCol[alt.refTable]?.[refCol];
      if (!sourceFieldId || !targetTableId || !targetFieldId) {
        warnings.push(`Unresolved FK ${alt.table}.${col} -> ${alt.refTable}.${refCol}`);
        continue;
      }
      const field = t.fields.find(f => f.id === sourceFieldId);
      if (field && !field.fk) field.fk = { table: targetTableId, field: targetFieldId };
      addRel(tId, sourceFieldId, targetTableId, targetFieldId);
    }
  }

  // Mark indexed fields
  for (const idx of indexes) {
    const t = tables.find(tt => tt.name === idx.table);
    if (!t) { warnings.push(`Index on unknown table "${idx.table}"`); continue; }
    for (const c of idx.columns) {
      const fid = fieldIdByCol[idx.table]?.[c];
      const field = fid && t.fields.find(f => f.id === fid);
      if (field) {
        if (idx.unique) field.unique = !field.pk;
        field.indexed = true;
      }
    }
  }

  return { schema: { tables, relationships }, warnings };
}
